version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=onlinestore
    container_name: my-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5431:5432"
  app:
    build: .
    ports:
      - "3333:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=onlinestore


volumes:
  pgdata:


